// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7X00sv--XE4JIwtwYWeqMDgzfoJZhF-s',
    appId: '1:867342415552:web:cc14a7f0b74569974a9f25',
    messagingSenderId: '867342415552',
    projectId: 'origami-learn-47587',
    authDomain: 'origami-learn-47587.firebaseapp.com',
    storageBucket: 'origami-learn-47587.firebasestorage.app',
    measurementId: 'G-V4D6EKEGB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWzy2Vo3PLOOWdpczDYQzuX9A3CBdNQU',
    appId: '1:867342415552:android:ea7ebad46a2136a54a9f25',
    messagingSenderId: '867342415552',
    projectId: 'origami-learn-47587',
    storageBucket: 'origami-learn-47587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOjyBoCDwV-LI-VG5lH70bcudLs0J3Ww',
    appId: '1:867342415552:ios:74bd0456efb9b8484a9f25',
    messagingSenderId: '867342415552',
    projectId: 'origami-learn-47587',
    storageBucket: 'origami-learn-47587.firebasestorage.app',
    iosBundleId: 'com.example.origamiLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOjyBoCDwV-LI-VG5lH70bcudLs0J3Ww',
    appId: '1:867342415552:ios:74bd0456efb9b8484a9f25',
    messagingSenderId: '867342415552',
    projectId: 'origami-learn-47587',
    storageBucket: 'origami-learn-47587.firebasestorage.app',
    iosBundleId: 'com.example.origamiLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7X00sv--XE4JIwtwYWeqMDgzfoJZhF-s',
    appId: '1:867342415552:web:d194d04b22fe27fc4a9f25',
    messagingSenderId: '867342415552',
    projectId: 'origami-learn-47587',
    authDomain: 'origami-learn-47587.firebaseapp.com',
    storageBucket: 'origami-learn-47587.firebasestorage.app',
    measurementId: 'G-4FS10866JV',
  );
}
